version: "3"

services:
  ngnix:
    container_name: fc3_proxy
    build:
      context: .
    tty: true
    ports:
      - 8080:80
    networks:
      - net-app
    depends_on:
      - node

  node:
    container_name: fc3_API
    build:
      context: ./app
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    networks:
      - net-app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: fc3_database
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_database
    ports:
      - 3306:3306
    networks:
      - net-app

networks:
  net-app:
    driver: bridge
